### ISSUE TITLE
unity_fixture.c defines its own setUp and tearDown causing problems with compilers not supporting the concept of 'weak' linkage.

### ISSUE THREAD

**Issue by damiandixon** [ThrowTheSwitch/Unity#423] opened 2019-05-09 07:32 UTC
While this is only defined when `UNITY_WEAK_ATTRIBUTE` and `UNITY_WEAK_PRAGMA` are **not** defined this does cause issues when you don't have the ability to use 'weak attribute' or 'weak pragma' because the compiler does not support them or the form that is supported is different from what is expected by the header.

Either way I would like to suggest the following:

```
#if !defined(UNITY_SETUP_TEARDOWN_DECLARED)
#if !defined(UNITY_WEAK_ATTRIBUTE) && !defined(UNITY_WEAK_PRAGMA)
void setUp(void)    { /*does nothing*/ }
void tearDown(void) { /*does nothing*/ }
#endif
#endif
```

This would allow someone to declare their own `setUp` and `tearDown` functions without the need to define `UNITY_WEAK_ATTRIBUTE ` or `UNITY_WEAK_PRAGMA`.

**Comment by Xenoamor** [comment] 2019-07-31 13:56
Is this not a duplicate of #417 which was resolved?

**Closed** 2019-10-23 11:58 UTC
