### ISSUE TITLE
Flush function can't be omitted

### ISSUE THREAD

**Issue by rikvdh** [ThrowTheSwitch/Unity#197] opened 2016-05-30 07:48 UTC
Hi,

We are using Unity with output-char putting a character directly to the console. But we can't omit the new Flush function added in commit c5c392b18a21b048ceb6f728bb7dea84c6e20db5. 

When I define UNITY_OUTPUT_FLUSH or UNITY_OUTPUT_FLUSH() it fails at the https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L308 declaration.

For `-D'UNITY_OUTPUT_FLUSH()'`:
`error: macro "UNITY_OUTPUT_FLUSH" passed 1 arguments, but takes just 0`

for `-DUNITY_OUTPUT_FLUSH`:
```
error: expected identifier or '(' before numeric constant
../Unity/src/unity_internals.h:308:13: note: in expansion of macro 'UNITY_OUTPUT_FLUSH'
 extern void UNITY_OUTPUT_FLUSH(void);
             ^
```

for `-DUNITY_OMIT_OUTPUT_FLUSH_HEADER_DECLARATION -DUNITY_OUTPUT_FLUSH`:
```
<command-line>:0:20: error: expected identifier or '(' before numeric constant
../Unity/src/unity.c:15:5: note: in expansion of macro 'UNITY_OUTPUT_FLUSH'
 int UNITY_OUTPUT_FLUSH(void);
     ^
```

for `-DUNITY_OMIT_OUTPUT_FLUSH_HEADER_DECLARATION -D'UNITY_OUTPUT_FLUSH()'`:
```
../Unity/src/unity.c:15:28: error: macro "UNITY_OUTPUT_FLUSH" passed 1 arguments, but takes just 0
 int UNITY_OUTPUT_FLUSH(void);
                            ^
```

I'm out of combinations. I also tried thinks like: `-D'UNITY_OUTPUT_FLUSH()'='(void)'`
I just want to omit this feature which is unneeded for our case.

Having odd forward declarations all over the shop seems a bit odd. Perhaps a UNITY_HAS_FLUSH and UNITY_FLUSH_FORWARD_DECL config options are more desirable than the current situation.

Kind regards,

Rik

**Comment by mvandervoord** [comment] 2016-05-30 13:01
Rik:

Thanks for delving into this issue! I've reproduced your results and agree with all your findings. I'm also not happy with how complex this minor feature is at the moment... it's something that is rarely used but is getting complicated for people to just ignore. 

The biggest problem with the current implementation is that it really wants to detect if the UNITY_OUTPUT_FLUSH macro has been defined as nothing. The only good way to do that is to use __VA_ARGS__ which isn't standard. So that's out.

I'll fiddle around with it a bit and get a something working. It might be something along the lines of what you suggest. If anyone else has thoughts, now is the time. ;)

**Comment by xor-gate** [comment] 2016-05-30 13:05
Current code is way to complex in configuration and you get a `#define` dependency hell which will kills users in-battle.

https://imgs.xkcd.com/comics/goto.png

**Comment by mvandervoord** [comment] 2016-05-30 13:34
*snicker* Well that was a colorful statement of support for revising this feature!

**Comment by xor-gate** [comment] 2016-05-30 13:38
I'm just joking around, I highly appreciate all contributions and hard work on the Unity library 👍. We should watch out we will not be delving into to much configuration options and should work-out-of-the-box(tm).

**Comment by mvandervoord** [comment] 2016-05-30 17:24
:) Anytime you can use XKCD in a comment is worthwhile.

Anyway, your statement on working out-of-the-box is exactly our goal. We try to make it Just Work (TM) for most users and then allow them to override default behavior where needed. This feature is definitely failing to meet that criteria at this point!

**Comment by xor-gate** [comment] 2016-05-30 17:50
Fhewj, happily we look all at the right direction!

**Comment by rikvdh** [comment] 2016-05-30 19:33
perhaps you can implicitly define UNITY_OUTPUT_FLUSH to fflush when you have `#ifdef __linux__` and omit `int UNITY_OUTPUT_FLUSH(void)` when `#if !defined(UNITY_OUTPUT_FLUSH) && !defined(__linux__)`.

**Comment by mvandervoord** [comment] 2016-06-21 14:47
I've made a few more tweaks to this feature. On my machine I can now do any of these without getting any errors or warnings. Travis also seems happy.

- define UNITY_OUTPUT_FLUSH to nothing.
- define UNITY_OUTPUT_FLUSH to be a custom macro 
- leave UNITY_OUTPUT_FLUSH undefined.

Since two machines aren't enough evidence to call something fixed, would you guys mind checking your own setups to see how the MAIN branch works for you?

**Comment by xor-gate** [comment] 2016-06-21 15:10
@mvandervoord thank you for your work, we will probably come back to this next week.

**Comment by mvandervoord** [comment] 2016-06-21 15:36
Cool. Let me know. :)

**Comment by xor-gate** [comment] 2016-06-24 11:08
@mvandervoord I have tested it and it works (for the flush function).
We only specifiy our own `UNITY_OUTPUT_CHAR` and seems to be enough.

@rikvdh you may close this issue.

**Comment by mvandervoord** [comment] 2016-06-24 11:38
awesome. Thanks for checking, @xor-gate

**Comment by xor-gate** [comment] 2016-06-24 11:45
I only got caught with a different problem but this has nothing todo with the flush see issue #200.

**Closed** 2016-06-29 13:52 UTC

**Comment by xor-gate** [comment] 2016-06-29 13:56
@rikvdh was way to busy to react :+). Thanks for closing @mvandervoord

**Comment by mvandervoord** [comment] 2016-06-29 13:58
:) I figure if he disagrees, he's welcome to reopen it.

**Comment by xor-gate** [comment] 2016-06-29 13:59
He sits in front of my desk, so I will hear it way earlier than the issue is reopened. Thanks :+1:
